# Generated by Django 5.1.3 on 2024-11-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCayTrong', '0002_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='webCayTrong/media/images/'),
        ),
    ]
