# Generated by Django 5.1.3 on 2024-11-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCayTrong', '0003_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
